services:
  caddy:
    image: ${COMPOSE_PROJECT_NAME}-caddy-dev
    build:
      target: caddy-dev
    environment:
      CADDY_ADMIN_OPTION: ${CADDY_ADMIN_OPTION:-}
      CADDY_DEBUG_OPTION: ${CADDY_DEBUG_OPTION:-debug}
    volumes:
      - ./config/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public/:/srv/public

  php:
    image: ${COMPOSE_PROJECT_NAME}-php-dev
    build:
      target: php-dev
      args:
        NODE_VERSION: ${NODE_VERSION:-lts}
    environment:
      COMPOSER_AUTH: ${COMPOSER_AUTH:-}
    volumes:
      - ./.:/var/www/html
      - ./config/docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
      - ./config/docker/php/php.ini:/usr/local/etc/php/conf.d/zz0-php.ini:ro
      - node_modules:/var/www/html/node_modules
      - var:/var/www/html/var
      - vendor:/var/www/html/vendor

  db:
    image: ${COMPOSE_PROJECT_NAME}-mariadb-dev
    build:
      target: mariadb-dev
    volumes:
      - ./config/docker/mariadb/mariadb.cnf:/etc/mysql/mariadb.conf.d/990-mariadb.cnf:ro

volumes:
  node_modules:
  var:
  vendor:
