name: Make release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip Folder
        run: zip -r ${{ github.event.repository.name }}.zip . -x ".git/*" ".github/*" "docker/*" "public/*" ".gitignore" "LICENSE" "README.md"

      - uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ github.event.repository.name }}.zip
